### ISSUE TITLE
Potential runtime panics detected by static analysis

### ISSUE THREAD

**Issue by lizhuohua** [Determinant/runes#1]
It is possible to construct malformed data structures or function arguments to trigger runtime panics.
For example, this triggers an integer overflow in function `load_prefix`:
```rust
use runes::utils::load_prefix;
use runes::utils::Read;

struct A {}

impl Read for A {
    fn read(&mut self, _buf: &mut [u8]) -> Option<usize> {
        None
    }
}

fn main() {
    load_prefix(&mut [1], 10, &mut A {});
}
```
And the following triggers a division-by-zero in function `Sampler::new`:
```rust
use runes::utils::Sampler;

fn main() {
    Sampler::new(0, 0);
}
```

**Comment by Determinant** [comment]
I'm not quite sure what this is really getting at as they're helper functions with specific assumptions and only used internally by the emulator (for example, it makes no sense to take 0 in either parameters of the Sampler). Closing this issue unless there is something else that's worth noting.
